In [1]:
# 라이브러리 및 환경 설정
import numpy as np

# 항상 같은 무작위 결과를 위해 시드 고정
np.random.seed(42)

### 1. 배열 초기화 및 속성 파악

In [5]:
# 5행 3열의 크기를 가지는 0부터 1 사이의 무작위 값으로 채워진 2차원 배열 X를 생성하세요.
X = np.random.random(size=(5, 3))

# 생성된 배열의 shape, size, ndim 속성을 출력하세요.
print("X의 모양:", X.shape)
print("X의 총 요소 수:", X.size)
print("X의 차원:", X.ndim)
print(X)

X의 모양: (5, 3)
X의 총 요소 수: 15
X의 차원: 2
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497]]


### 2. 브로드캐스팅 응용

In [8]:
# 1. 5x5 크기의 무작위 배열 M에 10을 더하는 연산을 수행하세요.
M = np.random.rand(5, 5)
M_scaled = M + 10

print(M)
print(M_scaled)

[[0.54269608 0.14092422 0.80219698 0.07455064 0.98688694]
 [0.77224477 0.19871568 0.00552212 0.81546143 0.70685734]
 [0.72900717 0.77127035 0.07404465 0.35846573 0.11586906]
 [0.86310343 0.62329813 0.33089802 0.06355835 0.31098232]
 [0.32518332 0.72960618 0.63755747 0.88721274 0.47221493]]
[[10.54269608 10.14092422 10.80219698 10.07455064 10.98688694]
 [10.77224477 10.19871568 10.00552212 10.81546143 10.70685734]
 [10.72900717 10.77127035 10.07404465 10.35846573 10.11586906]
 [10.86310343 10.62329813 10.33089802 10.06355835 10.31098232]
 [10.32518332 10.72960618 10.63755747 10.88721274 10.47221493]]


In [ ]:
# 2. 브로드캐스팅을 이용하여 2차원 배열 M의 각 열(Column)에 대해 다른 값(벡터 V)을 더하세요.
V = np.array([100, 200, 300, 400, 500])
# V를 (5, 1) 형태로 만들어 (5, 5) 배열 M에 브로드캐스팅 되도록 연산하세요.

# 브로드캐스팅을 이용한 덧셈
# reshape를 사용하여 V의 형태를 (5, 1)로 변경
    # -1은 자동으로 크기를 계산하도록 함
    # 1은 열의 개수를 의미
    # 따라서 V.reshape(-1, 1)은 V를 (5, 1) 형태로 변환
M_broad = M + V.reshape(-1, 1)
print("\nM + V (브로드캐스팅 결과):\n", M_broad)

(5,)
[[100]
 [200]
 [300]
 [400]
 [500]]
(5,)

M + V (브로드캐스팅 결과):
 [[100.54269608 100.14092422 100.80219698 100.07455064 100.98688694]
 [200.77224477 200.19871568 200.00552212 200.81546143 200.70685734]
 [300.72900717 300.77127035 300.07404465 300.35846573 300.11586906]
 [400.86310343 400.62329813 400.33089802 400.06355835 400.31098232]
 [500.32518332 500.72960618 500.63755747 500.88721274 500.47221493]]


### 3. 데이터 정규화

In [ ]:
# 100x2 크기의 평균 10, 분산 25인 데이터를 생성하세요.
    # 평균 10, 분산 25인 정규분포를 따르는 데이터를 생성하기 위해
    # np.random.randn() 함수를 사용하여 표준 정규분포(평균 0, 분산 1)를 따르는 데이터를 생성한 후,
    # 이를 원하는 평균과 분산으로 변환합니다.
    # 변환 공식: X_new = X * std + mean
    # 여기서 std는 표준편차(분산의 제곱근), mean은 원하는 평균입니다.
D = np.random.randn(100, 2) * 5 + 10 # 평균 10, 분산 25인 데이터

In [61]:
# D의 평균과 표준편차를 계산하세요.
answer_1 = D.mean()
answer_2 = D.std()

print(f'D의 평균: {answer_1}')
print(f'D의 표준편차: {answer_2}')

D의 평균: 10.766811630463174
D의 표준편차: 4.915912942612248


In [ ]:
# 위에서 계산한 D의 평균과 표준편차를 사용하여 D의 각 요소를 정규화합니다.
    # 정규화 공식: Z = (X - mean) / std
Z = (D - answer_1) / answer_2
print(Z)

[[ 0.51382312  1.88860364]
 [-0.33595952 -0.96793778]
 [-1.55889819 -0.89941825]
 [-0.18967921  1.66926831]
 [-0.68245068  0.07163026]
 [-0.17268941  1.05273523]
 [ 2.41417019 -0.69593492]
 [-0.65379694  0.90603573]
 [ 0.53756969  1.72230979]
 [ 0.43793072 -0.52142341]
 [ 0.44477243  0.97168244]
 [ 0.67853099  0.35996539]
 [ 0.92893464  1.03331088]
 [ 1.24981532  0.50382052]
 [-0.32596225 -0.00676237]
 [ 1.07116079 -0.98689502]
 [ 0.21899389 -0.5560525 ]
 [-0.12674909  1.14433428]
 [ 0.03838223 -0.10875475]
 [-1.53910218  0.60303269]
 [ 0.50053964  2.04427176]
 [-0.4690284   0.06691331]
 [ 0.09766381  1.44845014]
 [-0.25291117  0.12780861]
 [ 0.46230902  0.03381549]
 [-0.61005549  0.04142432]
 [ 0.9360107  -1.20005952]
 [-0.02074147 -0.86808203]
 [ 1.05950239 -1.70522673]
 [-0.72446785  0.22767851]
 [ 1.43631683 -0.22286052]
 [-0.72068186  1.7573488 ]
 [-1.62876789 -2.3924023 ]
 [ 0.29155533 -0.6666275 ]
 [-1.19468668  0.56448734]
 [ 0.09198534 -0.72971284]
 [-1.4581897   0.73139518]
 

### 4. 행렬 곱과 전치 응용

In [41]:
# 입력 데이터 X_input (10, 3)과 가중치 W (3, 1) 행렬을 생성하세요.
X_input = np.random.rand(10, 3)
W = np.random.rand(3, 1)

print(X_input)
print(W)

[[0.36646153 0.39617269 0.69546721]
 [0.3885581  0.44869362 0.23754413]
 [0.37325179 0.22726963 0.07319592]
 [0.60344859 0.6682128  0.61949035]
 [0.46349404 0.37978578 0.86333365]
 [0.51908179 0.47918188 0.02564207]
 [0.34124783 0.38019562 0.39882278]
 [0.58017237 0.53360255 0.60790509]
 [0.76488326 0.81298574 0.71812308]
 [0.9555237  0.01823258 0.19577799]]
[[0.00756287]
 [0.64747471]
 [0.89803055]]


In [ ]:
# X_input과 가중치 W를 행렬 곱하여 예측 결과(Y_pred)를 계산하세요.
Y_pred = X_input @ W

print(Y_pred)

[[0.8838341 ]
 [0.50677828]
 [0.21570637]
 [0.99353595]
 [1.02470703]
 [0.33721126]
 [0.60690291]
 [0.89579927]
 [1.17706889]
 [0.19484625]]


In [52]:
# X_input과 W를 전치하여 행렬곱을 수행하세요.
# (1, 10) 배열이 나오도록 연산하세요
Y_dot = W.T @ X_input.T
print("\n내적 연산 결과의 모양:", Y_dot.shape)


내적 연산 결과의 모양: (1, 10)


### extra. 역행렬 계산

In [73]:

# 정방 행렬 A를 생성하고, np.linalg.inv()를 사용하여 역행렬(A_inv)을 계산하세요.
# A @ A_inv 의 결과가 단위행렬(np.eye)과 같은지 확인하세요. (최적해 계산의 원리)
A = np.array([[4, 5], [2, 6]])
print(A)

# 역행렬 계산
    # np.linalg.inv() 함수는 정방 행렬의 역행렬을 계산
    # 역행렬은 원래 행렬과 곱했을 때 단위 행렬이 되는 행렬
A_inv = np.linalg.inv(A)

# A와 역행렬의 곱셈 
    # 최적화 문제에서 해를 구할 때, 역행렬을 이용하여 시스템의 해를 구할 수 있음
    # 단위행렬은 행렬 곱셈의 항등원 역할을 하기 때문에, 
    # A @ A_inv가 단위행렬이 되면 A_inv가 A의 진정한 역행렬임을 의미
I_check = A_inv @ A

print("\n 역행렬:\n", A_inv)
print("\n A @ A_inv (단위행렬 확인):\n", I_check)
print("\n 단위행렬:\n", np.eye(2, 2))

[[4 5]
 [2 6]]

 역행렬:
 [[ 0.42857143 -0.35714286]
 [-0.14285714  0.28571429]]

 A @ A_inv (단위행렬 확인):
 [[1.00000000e+00 2.22044605e-16]
 [0.00000000e+00 1.00000000e+00]]

 단위행렬:
 [[1. 0.]
 [0. 1.]]
